# data directory path
DATA_DIR: /ncdata

# the relative path from DATA_DIR of the directory where certs files are located
CERTS_DIR_RELATIVE_PATH: certs

# docker directory relative path from DATA_DIR
DOCKER_DIR_RELATIVE_PATH: ncdocker

# template opening delimiter
TEMPLATE_DELIMITERS:
  OPENING: '%%{'
  CLOSING: '}%%'

# config.yml default values
CONFIG_YML_DEFAULT_VALUES:
  MYSQL_ROOT_PASSWORD: nextcloud
  MYSQL_DATABASE: nextcloud
  MYSQL_PASSWORD: nextcloud
  MYSQL_USER: nextcloud
  PORT: 8080
  VIRTUAL_HOST: '""' # empty string
  SSL_PORT: 8443

# the relative path of a nextcloud custom docker file from /ncdata/ncdocker directory
CUSTOM_DOCKER_FILE_RELATIVE_PATH: app/Dockerfile

# the relative path of a nextcloud custom docker file from /ncdata/ncdocker directory
PROXY_DOCKER_FILE_RELATIVE_PATH: proxy/Dockerfile
